"""'Init'

Revision ID: 50d21283e8d2
Revises: a2b2b23a4286
Create Date: 2023-06-17 19:52:18.250233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d21283e8d2'
down_revision = 'a2b2b23a4286'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
