"""'Init'

Revision ID: 8d64b7ac107b
Revises: 50d21283e8d2
Create Date: 2023-06-17 20:36:21.841613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d64b7ac107b'
down_revision = '50d21283e8d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
